name: Build and deploy testing

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/upload-artifact@v2
      name: "Puplish Artifact"
      with:
        name: Jar Artifact
        path: /home/runner/work/Discord-Realtimeplayers/Discord-Realtimeplayers/target/SnapecraftBOT-1.0-SNAPSHOT.jar
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        data: '{"api": "/repos/$GITHUB_REPOSITORY/actions/artifacts"}'
